### ISSUE TITLE
Switch to NamedRules, etc.

### ISSUE THREAD

**Issue by prostomarkeloff** [avrogachev/vk_quest_bot#1]
Hello! I looked at your code and decided to give advice, use [NamedRule](https://github.com/prostomarkeloff/vk.py/blob/master/examples/bot_framework/named_rule.py) instead of the usual rules. They look less bulky and nicer in code. In addition to this, I would advise you to take out middlewares and rules in separate files. Also you can use [blueprints](https://github.com/prostomarkeloff/vk.py/blob/master/examples/bot_framework/blueprints.py). Good luck!

**Comment by avrogachev** [comment]
Thank you so much for your work! The bot withstood a lot and was able to withstand the attack of 350 users for 6 hours of the city quest, all thanks to the excellent module. I will gradually finish it, the closer the deadline was - the more simple and primitive the decisions were. Thank you very much!

**Comment by prostomarkeloff** [comment]
360 - it is a little :) Thank you!
